name: Dispatch NPM Release

on:
  workflow_dispatch:
    inputs:
      build_mode:
        type: choice
        description: Build Mode (patch | minor | major)
        options:
          - patch
          - minor
          - major

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Git
        run: |
          git config user.name "mt-ci gh-action"
          git config user.email "mt-ci@gh-action.none"
          git config advice.addIgnoredFile false
          git config advice.detachedHead false

      - name: Verify build_mode
        run: |
          echo "mt-ci build_mode: ${{ github.event.inputs.build_mode }}"

      - name: Install dependencies and build ðŸ”§
        run: |
          npm install -g pnpm
          pnpm install

      - name: Versioning application artifact
        run: |
          RELEASE_MODE=${{ github.event.inputs.build_mode }}

          pnpm --filter ./packages/node version $RELEASE_MODE
          pnpm --filter ./packages/next version $RELEASE_MODE
          pnpm --filter ./packages/react version $RELEASE_MODE

      - name: Publish package on NPM ðŸ“¦
        run: |
          pnpm release:node
          pnpm release:next
          pnpm release:react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Patch latest version to Git
        run: |
          git add .
          git commit -m "Version: $VERSION | Rebuild latest src"
          git push origin main
